### PR TITLE
Revert "Second milestone"

### PR DESCRIPTION
**Pull request by Tresor11**
on this branch i:
- Created the different components
- add the validations for props

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @Tresor11 , 

This is a re-review, but i can't see former review, nor coding files you've worked on
Wassup with your repository or branch organisation here ?? lol

### Please review all these and re-submit......... there's nothing to review

**Comment by Tresor11** [comment]
**While solving the conflict I accidentally merged the branch** so this is a revert branch

- [the first review can be found here](https://github.com/Tresor11/react-calculator/pull/2)

**Review by shloch — APPROVED** [review]
## Hello @Tresor11 

Good to go......see you in milestone 3

accomplished

### styling time

**Comment by Tresor11** [comment]
Thanks Louis

**Pull request merged**
